# Generated by Django 5.2.9 on 2026-02-15 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Kullanıcı Adı')),
                ('password_hash', models.CharField(max_length=256, verbose_name='Şifre Hash')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Soyad')),
                ('role', models.CharField(choices=[('superadmin', 'Süper Admin'), ('admin', 'Admin')], default='admin', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Son Giriş')),
                ('can_manage_sliders', models.BooleanField(default=True, verbose_name='Slider Yönetimi')),
                ('can_manage_services', models.BooleanField(default=True, verbose_name='Hizmet Yönetimi')),
                ('can_manage_gallery', models.BooleanField(default=True, verbose_name='Galeri Yönetimi')),
                ('can_manage_messages', models.BooleanField(default=True, verbose_name='Mesaj Yönetimi')),
                ('can_manage_faq', models.BooleanField(default=True, verbose_name='SSS Yönetimi')),
                ('can_manage_about', models.BooleanField(default=True, verbose_name='Hakkımızda Yönetimi')),
            ],
            options={
                'verbose_name': 'Admin Kullanıcı',
                'verbose_name_plural': 'Admin Kullanıcılar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Denenen Kullanıcı Adı')),
                ('success', models.BooleanField(default=False, verbose_name='Başarılı')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deneme Zamanı')),
            ],
            options={
                'verbose_name': 'Giriş Denemesi',
                'verbose_name_plural': 'Giriş Denemeleri',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='custom_admi_ip_addr_82a151_idx')],
            },
        ),
    ]
