# Generated by Django 5.2.9 on 2025-12-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('short_content', models.TextField(max_length=500, verbose_name='Kısa İçerik (Anasayfa için)')),
                ('full_content', models.TextField(verbose_name='Tam İçerik')),
                ('image', models.FileField(blank=True, null=True, upload_to='about/', verbose_name='Resim')),
                ('company_name', models.CharField(default='Nakliye Firması', max_length=200, verbose_name='Firma Adı')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Çalışma Saatleri')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('image', models.FileField(upload_to='gallery/', verbose_name='Resim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Galeri Resmi',
                'verbose_name_plural': 'Galeri Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('short_description', models.TextField(max_length=300, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('image', models.FileField(upload_to='services/', verbose_name='Resim')),
                ('icon', models.CharField(default='fa-truck', max_length=50, verbose_name='İkon (Font Awesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('image', models.FileField(upload_to='slider/', verbose_name='Resim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Slider Resmi',
                'verbose_name_plural': 'Slider Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('room_count', models.CharField(choices=[('1+0', '1+0 (Stüdyo)'), ('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('5+1', '5+1 ve üzeri'), ('villa', 'Villa'), ('ofis', 'Ofis')], max_length=20, verbose_name='Oda Sayısı')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
