# Generated by Django 5.2.9 on 2025-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('evden_eve', 'Evden Eve Nakliyat'), ('sehirler_arasi', 'Şehirler Arası Nakliyat'), ('ofis', 'Ofis Taşımacılığı'), ('paketleme', 'Paketleme Hizmeti'), ('mobilya', 'Mobilya Montajı')], default='', max_length=50, verbose_name='Konu'),
            preserve_default=False,
        ),
    ]
