"""
Django settings for nakliye project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1*!e+&0!)-2**+dse(jhuh#3wy#a^7by1r!k9m4x(402jgld8h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["134.209.199.175", "www.ayildiznakliyat.com", "ayildiznakliyat.com", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'core',
    'custom_admin',  # Özel admin paneli
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'custom_admin.middleware.AdminRouteMaskMiddleware',       # Bilinen admin URL'lerini maskele
    'custom_admin.middleware.AdminIPRestrictionMiddleware',    # IP bazlı erişim kısıtlama
]

ROOT_URLCONF = 'nakliye.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'custom_admin.context_processors.admin_context',  # Admin panel context
            ],
        },
    },
]

WSGI_APPLICATION = 'nakliye.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# E-posta Ayarları
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ayyildiznakliyat.23@gmail.com'
EMAIL_HOST_PASSWORD = 'bkzj lkwi nqsg zvkd'  
DEFAULT_FROM_EMAIL = 'Ay Yıldız Nakliyat <ayyildiznakliyat.23@gmail.com>'

# Bildirim Ayarları
NOTIFICATION_EMAIL = 'ayyildiznakliyat.23@gmail.com'
NOTIFICATION_PHONE = '05438092323'

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')

# WhiteNoise: Static dosyaları sıkıştır ve cache'le
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==========================================
# Custom Admin Panel Ayarları
# ==========================================

# Admin paneli gizli route - tahmin edilemez olmalı!
# Bu değeri değiştirerek admin URL'ini özelleştirebilirsiniz.
ADMIN_PANEL_ROUTE = os.environ.get('ADMIN_PANEL_ROUTE', 'gizli-yonetim-x7c8v9')

# IP bazlı erişim kısıtlama (boş liste = tüm IP'lere açık)
# Sadece belirli IP'lerden erişime izin vermek için:
# ADMIN_ALLOWED_IPS = ['192.168.1.1', '10.0.0.1']
ADMIN_ALLOWED_IPS = os.environ.get('ADMIN_ALLOWED_IPS', '').split(',') if os.environ.get('ADMIN_ALLOWED_IPS') else []

# Brute-force koruması ayarları
ADMIN_MAX_LOGIN_ATTEMPTS = int(os.environ.get('ADMIN_MAX_LOGIN_ATTEMPTS', 5))  # Maks başarısız deneme
ADMIN_LOCKOUT_MINUTES = int(os.environ.get('ADMIN_LOCKOUT_MINUTES', 15))       # Kilitleme süresi (dk)

# Güvenlik başlıkları
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 3600  # 1 saat oturum süresi
SESSION_EXPIRE_AT_BROWSER_CLOSE = True