# Generated by Django 5.2.9 on 2025-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
