# Generated by Django 5.2.9 on 2025-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('evden_eve', 'Evden Eve Nakliyat'), ('sehirler_arasi', 'Şehirler Arası Nakliyat'), ('ofis', 'Ofis Taşımacılığı'), ('paketleme', 'Paketleme Hizmeti'), ('mobilya', 'Mobilya Montajı')], default='evden_eve', max_length=50, verbose_name='Konu'),
        ),
    ]
